version: '3'

services:
  postgres:
    image: postgres:10.6-alpine
    volumes:
      - postgres-store:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  redis:
    image: redis:latest
    volumes:
      - redis-store:/data
    command: redis-server --appendonly yes

  rails:
    build: ./auto-matching-api-rails/
    command: /bin/sh -c "rm -rf /app/tmp/pids/server.pid && bin/rails server -b 0.0.0.0 -p 3000"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_HOST: postgres
      REDIS_URL: redis://redis:6379
    ports:
      - '5000:3000'
    tty: true
    volumes:
      - ./auto-matching-api-rails:/app
      - bundler-store:/usr/local/bundle
      - /dev/shm:/dev/shm

  nuxt:
    build: ./auto-matching-nuxt/
    command: /bin/sh -c 'API_URL=http://rails:3000 yarn dev'
    environment:
      HOST: 0.0.0.0
    ports:
      - '3000:3000'
    tty: true
    volumes:
      - ./auto-matching-nuxt:/app
      - node-modules-store:/app/node_modules
    working_dir: /app

  worker:
    build: ./auto-matching-api-rails/.
    command: bundle exec sidekiq
    environment:
      DATABASE_HOST: postgres
      REDIS_URL: redis://redis:6379
    volumes:
      - ./auto-matching-api-rails:/app
      - bundler-store:/usr/local/bundle
      - /dev/shm:/dev/shm
    depends_on:
      - postgres
      - redis

  docusaurus:
    build: ./auto-matching-docs/
    ports:
      - '3001:3000'
      - 35729:35729
    tty: true
    volumes:
      - ./auto-matching-docs/docs:/app/docs
      - ./auto-matching-docs/website/blog:/app/website/blog
      - ./auto-matching-docs/website/core:/app/website/core
      - ./auto-matching-docs/website/i18n:/app/website/i18n
      - ./auto-matching-docs/website/pages:/app/website/pages
      - ./auto-matching-docs/website/static:/app/website/static
      - ./auto-matching-docs/website/sidebars.json:/app/website/sidebars.json
      - ./auto-matching-docs/website/siteConfig.js:/app/website/siteConfig.js
    working_dir: /app/website

volumes:
  postgres-store:
  redis-store:
  bundler-store:
  node-modules-store:
