swagger: '2.0'
info:
  title: Auto Matching
  description: API description in Markdown.
  version: 1.0.0
host: 'localhost:5000'
schemes:
  - http
paths:
  /api/users/source-sites:
    get:
      summary: サイト一覧
      produces:
        - application/json
      responses:
        '200':
          description: 成功時のレスポンス
        '500':
          description: 失敗時のレスポンス
  /api/users/source-sites/{id}:
    put:
      summary: サイト情報更新
      produces:
          - application/json
      parameters:
        - name: "id"
          in: "path"
          type: integer
        - in: body
          name: attributes
          description: サイト情報
          schema:
            type: object
            properties:
              id:
                type: integer
              loginId:
                description: "ログインID"
                type: string
              loginPassword:
                description: "ログインパスワード"
                type: string
              activateFlag:
                descrition: "有効フラグ"
                type: boolean
      responses:
        '200':
          description: 成功時のレスポンス
        '500':
          description: 失敗時のレスポンス
