development:
  adapter: redis

test:
  adapter: redis

production:
  adapter: redis
  url: <%= ENV.fetch("REDISTOGO_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: auto-matching-api-rail_production
