default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  pool: 5

development:
  <<: *default
  database: auto-matching_development

test:
  <<: *default
  database: auto-matching_test

production:
  <<: *default
  database: auto-matching_production
  url: <%= ENV['DATABASE_URL'] %>
