default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>

development:
  <<: *default
  database: auto-matching_development

test:
  <<: *default
  database: auto-matching_test

production:
  <<: *default
  database: auto-matching_production
  url: <%= ENV['DATABASE_URL'] %>
  pool: 5
