queue_ahead: 360
queue_name: "default"
tz: "Asia/Tokyo"

simple_task:
  class: "ActiveJob"
  every: "1.day"
  at: "11:00"
  expires_after: "23.hours"
  : "2.minutes"

overnight_task:
  class: "SomeSidekiqWorker"
  every: "1.day"
  at: "4:00"
  expires_after: "1.hours"
